### ISSUE TITLE
SVN deploy

### ISSUE THREAD

**Issue by brint** [rackspace-cookbooks/magentostack#202]
How much effort would it take to add a subversion deployment option? We've had a couple that could use this stack that were hosted via subversion.

**Comment by martinb3** [comment]
I think it would be fairly trivial. We'd just use the `subversion` resource instead of the `git` one. It would also be easy to set the appropriate attribute in a customer's wrapper cookbook so that magentostack leaves the code deployment to the wrapper, and use the subversion resource in the wrapper instead.

**Comment by martinb3** [comment]
Perhaps 1-2 hours of work max.

**Comment by brint** [comment]
Okay. This is something we need to add.

**Comment by martinb3** [comment]
The only immediate thing that I ran into when looking at this deeper was authentication. Github only allows SVN checkouts over HTTPS, so you're required to use password or token authentication. Our tests will be using a token for auth when doing SVN checkouts over HTTPS.

We'll support all the parameters on SVN, though, so downstream can use any auth supported by the [subversion resource](https://docs.chef.io/resource_subversion.html) in chef.
